name: Dart Package CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FLUTTER_VERSION: '3.27.4'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }} 

    - name: Set up Dart SDK
      uses: dart-lang/setup-dart@v1
      with:
        sdk: stable

    - name: Clean dependencies
      run: flutter clean
  
    - name: Install dependencies
      run: flutter pub get
      
    - name: Check formatting
      run: dart format --set-exit-if-changed

    - name: Run Unit Tests
      run: flutter test
      continue-on-error: false 
      
      
        # - name: Run tests
    #   run: dart test
    #   continue-on-error: false

  publish:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v') # Publish only for tagged releases
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Dart SDK
      uses: dart-lang/setup-dart@v1
      with:
        sdk: stable

    - name: Install dependencies
      run: dart pub get

    - name: Dry run publish
      run: dart pub publish --dry-run

    # - name: Publish to pub.dev
    #   env:
    #     PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}
    #   run: echo "$PUB_CREDENTIALS" > ~/.pub-cache/credentials.json && dart pub publish -f
